### ISSUE TITLE
Does this support app router feature introduced in Next13 ?

### ISSUE THREAD

**Issue by arunvishnun** [stefee/fastify-next#91]
I guess the question is clear from title, Wondering if this package supports app router ?

**Comment by stefee** [comment]
> I guess the question is clear from title, Wondering if this package supports app router ?

I expect so although I haven't actually tried it.

However, I expect this package will be deprecated within the next year so I probably wouldn't adopt it unless it's only for short-term use. I personally recommend using the Next.js [standalone output mode](https://nextjs.org/docs/app/api-reference/next-config-js/output) instead of wrapping with a Fastify server. If you really need both Fastify and Next.js routes served on the same host, I recommend hosting them both as standalone services and a reverse proxy (such as Nginx) to route traffic between them.

**Comment by stefee** [comment]
Switched to using App Router on the example on the main branch. 🙏🏻
